### ISSUE TITLE
Request: New release

### ISSUE THREAD

**Issue by michaeldbianchi** [daichirata/gcsproxy#12]
Hello @daichirata 

Firstly, thank you for maintaining this project. It's fairly simple but very useful in the right context. 

I was looking to use the new support for the `If-Modified-Since` headers, and was hoping you could draft a new release with the updated code. In the meantime, I can just build it myself, but it'd be nice to have an official release.

Thank you!

**Comment by daichirata** [comment]
Hello @michaeldbianchi 

Thank you for your report. We have just released a new version v0.3.1 with the `If-Modified-Since` fix.

Thank you!
