### ISSUE TITLE
Clients that do not accept gzip-encoding are not handled properly

### ISSUE THREAD

**Issue by dylan-tock** [daichirata/gcsproxy#15]
The serving behavior does not change if a client provides an `Accept-Encoding` header with `gzip` included or if it does not.  This means GCS items that are gzip'd will be served compressed and clients that cannot grok gzip'd content will fail.

I am submitting a corresponding PR to address the issue.

**Comment by daichirata** [comment]
Thanks for the report and great fixes. We have released v0.3.2 which incorporates the fixes.
