### ISSUE TITLE
Bucket regex does not allow domain names in buckets

### ISSUE THREAD

**Issue by jf647** [daichirata/gcsproxy#2]
Google Cloud Storage buckets can contain dot characters:

https://cloud.google.com/storage/docs/naming

and are typically used with domain names (if you verify you own the domain):

https://cloud.google.com/storage/docs/domain-name-verification

The handler regex currently does not deal with buckets like foo.example.com; it just returns a 404 error without getting into the proxy() function.

**Comment by daichirata** [comment]
Thank you for reporting. fe14967787c46b01b9aef4b5b2f82f4784a9572d fixed that problem and released v0.3.0.
